<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recruitment.Dto\Recruitment.Dto.csproj" />
  </ItemGroup>

</Project>
